# Generated by Django 4.2.27 on 2025-12-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentnotification_notificationsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointmentnotification',
            name='type',
            field=models.CharField(choices=[('greeting_30', 'Saudação 30 min'), ('alert_15', 'Alerta 15 min'), ('alert_10', 'Alerta 10 min')], max_length=20),
        ),
    ]
