# Generated by Django 4.2.27 on 2025-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointmentnotification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnotification',
            name='type',
            field=models.CharField(choices=[('greeting_30', 'Saudação 30 min'), ('alert_15', 'Alerta 15 min'), ('alert_10', 'Alerta 10 min'), ('alert_0', 'Na hora'), ('confirmation', 'Confirmação')], max_length=20),
        ),
    ]
